### ISSUE TITLE
Not good with Linux

### ISSUE THREAD

**Issue by Kismeras** [alexlance/sms-mms-import-to-signal#2]
Do you have a video tutorial or maybe a more detailed walk through on how to do this? I am not an expert with Linux and I don't know what to do after I've installed the backup-tool.

**Comment by alexlance** [comment]
Hi Kismeras, sorry it would take a couple of hours to put together a video tutorial - unless you're willing to pay for that time I can't see it happening.

If you follow the README document as closely as possible and report back:

1) exactly where you get stuck in the document (a line number in the file)
2) what exact command you ran and 
3) what exact error message you get

I might be able to offer you some suggestions.

(It's worth noting that if you're not using Linux my knowledge of how to help you becomes much smaller)
